### ISSUE TITLE
asjcore crash on start

### ISSUE THREAD

**Issue by jrslwstark** [FalsePattern/GasStation#4] opened 2022-10-04 12:14 UTC
[fml-client-latest.log](https://github.com/FalsePattern/GasStation/files/9706578/fml-client-latest.log)

**Comment by DrParadox7** [comment] 2022-10-22 17:15
Duplicate of #5

**Comment by FalsePattern** [comment] 2022-12-21 20:14
Fixed in 0.5.0

**Closed as completed** 2022-12-22 18:19 UTC
